Update WearableComponent.php
CustomiesDevs/Customies pull request #110
Opened 2023-10-09 16:16 UTC by theohdg2

With the new versions of Minecraft, we no longer saw the armor protection on the HUD,
[https://learn.microsoft.com/en-us/minecraft/creator/reference/content/itemreference/examples/itemcomponents/minecraft_wearable](Minecraft Armor component)

2023-10-26 14:05 UTC, dadodasyra requested changes
The whole indentation is f upped. Align on the current one.

2023-10-26 14:05 UTC, dadodasyra commented on src/item/ItemComponentsTrait.php
> +
Why ?

2023-10-26 14:05 UTC, dadodasyra commented on .gitignore
> +PocketMine-MP.phar
Why ?

2023-10-26 14:05 UTC, dadodasyra commented on src/item/ItemComponentsTrait.php
> +        }
You should use a match case in enchantable_slot for the value. For the rest it's similar in every case so...

2023-10-26 14:05 UTC, dadodasyra commented on src/item/ItemComponentsTrait.php
> +        }
Empty if case ? why ?

2023-10-26 14:05 UTC, dadodasyra commented on src/item/ItemComponentsTrait.php
> +			$this->addComponent(new WearableComponent($slot,$this->getDefensePoints()));
missing a space after the comma

2023-10-26 14:05 UTC, dadodasyra commented on src/item/component/WearableComponent.php
> +	public function __construct(string $slot,int $protection) {
missing a space after the comma

2023-10-26 14:05 UTC, dadodasyra commented on src/item/ItemComponentsTrait.php
> +        }
And you should use " instead of '

2023-10-26 14:05 UTC, dadodasyra commented on src/item/ItemComponentsTrait.php
> +        ];
why is this defined so early as it's only used in one case ? it could also be replaced with a match case

2023-10-26 14:05 UTC, dadodasyra commented on src/item/ItemComponentsTrait.php
> +        ];
Btw i doubt about the "armor_torso"

2023-10-26 14:05 UTC, dadodasyra commented on src/item/ItemComponentsTrait.php
> +        ];
Use " instead of '

2023-10-26 14:39 UTC, theohdg2 commented
Normally, I solved all the little problems you told us

2023-10-26 14:42 UTC, theohdg2 commented
And if it is indeed "armor_torso" that should be used, you can do a simple github search and see that

2023-11-03 21:10 UTC, dadodasyra requested changes
Seems like you forgot some of them. You should take a look at the preview in "Files changed" where you can correctly see what i'm talking about.
By the way your "fix" was to reformat the whole ItemComponentsTrait, it means that the PR becomes difficult to review as github thinks that the whole file was modified..

2023-11-03 21:10 UTC, dadodasyra commented on src/item/component/WearableComponent.php
> +        $this->protection = $protection;
indentaiton

2023-11-03 21:10 UTC, dadodasyra commented on src/item/component/WearableComponent.php
> +            "protection" => $this->protection
indentation

2023-11-03 21:10 UTC, dadodasyra commented on src/block/Model.php
> +        $this->collision_enable = $collision_enable;
indentaiton

2023-11-03 21:10 UTC, dadodasyra commented on src/block/Model.php
> +	public function __construct(array $materials, ?string $geometry = null, ?Vector3 $origin = null, ?Vector3 $size = null,$collision_enable = true) {
space before ","

2023-11-03 21:10 UTC, dadodasyra commented on src/block/Model.php
> +    private bool $collision_enable;
indentaiton

2023-11-04 18:16 UTC, dadodasyra commented
I'm not owning or managing this repo at all but this PR seems like a mess for me, even the title is random. There's surely some cherry picking and some work to take here. But I don't think it will be merged as it looks now.

2023-11-07 16:30 UTC, xLordShadow commented
Oh this is a mess. Ill try to clean it up so i can have the wearable component working soon.

2023-11-07 16:48 UTC, xLordShadow commented
It wont let me commit my changes :(

2023-11-07 16:58 UTC, xLordShadow commented on src/block/Model.php
> +	public function __construct(array $materials, ?string $geometry = null, ?Vector3 $origin = null, ?Vector3 $size = null,$collision_enable = true) {
And boolean typecast

2023-11-07 17:01 UTC, xLordShadow commented on src/item/ItemComponentsTrait.php
Why is the item texture saved? Its not used anywhere else and getTextureString is not used as well.

Change the enchantable_slot and enchantable_value from being in getComponents() and move it to initComponent and use the enchantable component class. 

Rather than 0,1,2,3 for armor slots, follow the format in initComponent where is uses the ArmorInventory::HEAD_SLOT

2023-11-07 17:02 UTC, xLordShadow commented on src/item/component/EnchantableComponent.php
This requires a "value" field for the enchantability as stated [here](https://bedrock.dev/docs/stable/Item#minecraft%3Aenchantable).

2024-03-28 21:44 UTC, closed without merging

2024-03-28 21:44 UTC, unickorn commented
After a good while, I've decided to close this PR due to an enormous mess of formatting and type issues and unresolved conversations. If anyone would like to clean up a fork of this and make a proper merge request I'd be more than happy to review.

Thank you for your interest and time @theohdg2, feel free to check and resolve the reviews and comments others left you and reopen the issue! :)