[FIX]: DiggerComponent use_efficiency property added
CustomiesDevs/Customies pull request #133
Opened 2024-06-14 10:21 UTC by Refaltor77

2024-06-27 18:10 UTC, dadodasyra requested changes

2024-06-27 18:10 UTC, dadodasyra commented on .gitignore
> +PocketMine-Maa.phar
This has nothing to do here

2024-06-27 18:10 UTC, dadodasyra commented on src/item/component/DiggerComponent.php
> +            "use_efficiency" => true
you should use the same indentation has customies (tabulations not spaces)

2024-06-27 18:10 UTC, dadodasyra commented on src/item/component/IconComponent.php
> +                'default' => $this->texture
customies uses " and not ' everywhere in it's code, changing that makes no sense and is decreasing code quality (+ indentation is still tabulations)

2024-06-27 18:11 UTC, dadodasyra commented
What is your code changing ? what's the purpose of adding this value ?

2024-11-03 16:05 UTC, TwistedAsylumMC commented
Closing due to changing other stuff that's irrelevant

2024-11-03 16:05 UTC, closed without merging